# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('nombre_inscriptions', models.PositiveIntegerField(default=0, verbose_name='Inscriptions')),
                ('nombre_nouveaux_agents', models.PositiveIntegerField(default=0, verbose_name='Nouveaux agents')),
                ('nombre_biens_publies', models.PositiveIntegerField(default=0, verbose_name='Biens publiés')),
                ('nombre_vues_total', models.PositiveIntegerField(default=0, verbose_name='Vues total')),
                ('nombre_messages', models.PositiveIntegerField(default=0, verbose_name='Messages')),
                ('nombre_favoris', models.PositiveIntegerField(default=0, verbose_name='Favoris')),
                ('revenus_abonnements_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenus abonnements (USD)')),
                ('revenus_boosts_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenus boosts (USD)')),
                ('nombre_boosts_actifs', models.PositiveIntegerField(default=0, verbose_name='Boosts actifs')),
            ],
            options={
                'verbose_name': 'Statistique journalière',
                'verbose_name_plural': 'Statistiques journalières',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VueBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('duree_visionnage_sec', models.PositiveIntegerField(default=0, verbose_name='Durée de visionnage (sec)')),
                ('est_lecture_complete', models.BooleanField(default=False, verbose_name='Lecture complète')),
                ('source', models.CharField(blank=True, default='fil', max_length=50, verbose_name='Source')),
                ('date_vue', models.DateTimeField(auto_now_add=True, verbose_name='Date de vue')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='biens.bienimmobilier', verbose_name='Bien')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vues_biens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vue de bien',
                'verbose_name_plural': 'Vues de biens',
                'ordering': ['-date_vue'],
            },
        ),
    ]
