# Generated by Django 5.2.11 on 2026-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('bureau', 'Bureau / Commerce'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('villa', 'Villa'), ('immeuble', 'Immeuble'), ('entrepot', 'Entrepôt'), ('autre', 'Autre')], max_length=30, verbose_name='Type de bien')),
                ('type_offre', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location'), ('colocation', 'Colocation'), ('location_meublee', 'Location meublée'), ('vente_terrain', 'Vente de terrain')], max_length=30, verbose_name="Type d'offre")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (USD)')),
                ('devise', models.CharField(default='USD', max_length=5, verbose_name='Devise')),
                ('nombre_chambres', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de chambres')),
                ('nombre_salles_bain', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de salles de bain')),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface (m²)')),
                ('avenue', models.CharField(blank=True, default='', max_length=200, verbose_name='Avenue / Rue')),
                ('numero_adresse', models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('publie', 'Publié'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut')),
                ('est_booste', models.BooleanField(db_index=True, default=False, verbose_name='Est boosté')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('nombre_favoris', models.PositiveIntegerField(default=0, verbose_name='Nombre de favoris')),
                ('nombre_partages', models.PositiveIntegerField(default=0, verbose_name='Nombre de partages')),
                ('nombre_contacts', models.PositiveIntegerField(default=0, verbose_name='Nombre de contacts')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens/images/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, default='', max_length=200, verbose_name='Légende')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image de bien',
                'verbose_name_plural': 'Images de biens',
                'ordering': ['ordre'],
            },
        ),
    ]
