# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        ('localisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'type_compte': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='localisations.commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='localisations.quartier', verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='localisations.ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='imagebien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='biens.bienimmobilier', verbose_name='Bien'),
        ),
        migrations.AddIndex(
            model_name='bienimmobilier',
            index=models.Index(fields=['statut', 'est_booste', '-date_creation'], name='biens_bieni_statut_f61add_idx'),
        ),
        migrations.AddIndex(
            model_name='bienimmobilier',
            index=models.Index(fields=['type_bien', 'type_offre'], name='biens_bieni_type_bi_ecdd57_idx'),
        ),
        migrations.AddIndex(
            model_name='bienimmobilier',
            index=models.Index(fields=['ville', 'commune'], name='biens_bieni_ville_i_371d54_idx'),
        ),
        migrations.AddIndex(
            model_name='bienimmobilier',
            index=models.Index(fields=['prix'], name='biens_bieni_prix_42a32b_idx'),
        ),
    ]
