# Generated by Django 5.2.11 on 2026-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='quartier_texte',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Quartier (texte libre)'),
        ),
    ]
