# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('localisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(blank=True, default='', max_length=100, verbose_name='Post-nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('type_compte', models.CharField(choices=[('simple', 'Utilisateur simple'), ('agent', 'Agent immobilier'), ('administrateur', 'Administrateur')], db_index=True, default='simple', max_length=20, verbose_name='Type de compte')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('est_verifie', models.BooleanField(default=False, verbose_name='E-mail vérifié')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès staff')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('derniere_connexion_enregistree', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion enregistrée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('role_admin', models.CharField(choices=[('directeur', 'Directeur'), ('moderateur', 'Modérateur / Gouvernance'), ('gest_abonnements', 'Gestionnaire abonnements'), ('gest_support', 'Gestionnaire support'), ('gest_marketing', 'Gestionnaire marketing / boost'), ('superviseur', 'Superviseur')], default='moderateur', max_length=30, verbose_name='Rôle administrateur')),
                ('est_en_ligne', models.BooleanField(default=False, verbose_name='En ligne')),
                ('derniere_activite', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
            },
        ),
        migrations.CreateModel(
            name='JournalConnexionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_connexion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de connexion')),
                ('heure_deconnexion', models.DateTimeField(blank=True, null=True, verbose_name='Heure de déconnexion')),
                ('duree_session_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée session (min)')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_connexion', to='comptes.profiladministrateur', verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Journal de connexion admin',
                'verbose_name_plural': 'Journaux de connexion admin',
                'ordering': ['-heure_connexion'],
            },
        ),
        migrations.CreateModel(
            name='JournalActiviteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Détail')),
                ('objet_type', models.CharField(blank=True, default='', max_length=100, verbose_name="Type d'objet")),
                ('objet_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'action")),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_activite', to='comptes.profiladministrateur', verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': "Journal d'activité admin",
                'verbose_name_plural': "Journaux d'activité admin",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_professionnel', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom professionnel')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biographie')),
                ('numero_licence', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de licence')),
                ('adresse_bureau', models.CharField(blank=True, default='', max_length=300, verbose_name='Adresse du bureau')),
                ('site_web', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('est_verifie_agent', models.BooleanField(default=False, verbose_name='Agent vérifié')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agent', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('ville_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisations.ville', verbose_name='Ville principale')),
            ],
            options={
                'verbose_name': 'Profil agent',
                'verbose_name_plural': 'Profils agents',
            },
        ),
    ]
