# Generated by Django 5.2.11 on 2026-03-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiladministrateur',
            name='role_admin',
            field=models.CharField(choices=[('directeur', 'Directeur (Super Admin)'), ('gestion', 'Admin Gestion'), ('moderateur', 'Modérateur'), ('support', 'Support (Service client)')], default='moderateur', max_length=30, verbose_name='Rôle administrateur'),
        ),
    ]
