# Generated by Django 5.2.11 on 2026-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_profiladministrateur_role_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiladministrateur',
            name='role_admin',
            field=models.CharField(choices=[('directeur', 'Directeur (Super Admin)'), ('gestion', 'Gestionnaire'), ('moderateur', 'Modérateur')], default='moderateur', max_length=30, verbose_name='Rôle administrateur'),
        ),
    ]
