# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('abonnement', "Inclus dans l'abonnement"), ('achat', 'Achat unitaire')], max_length=20, verbose_name='Source du boost')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], db_index=True, default='actif', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('score_boost', models.PositiveIntegerField(default=100, help_text='Score de priorité pour le classement (0-1000)', verbose_name='Score de boost')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions')),
                ('clics', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Boost vidéo',
                'verbose_name_plural': 'Boosts vidéo',
                'ordering': ['-date_debut'],
            },
        ),
    ]
