# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boosts', '0001_initial'),
        ('paiements', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boostvideo',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='boostvideo',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosts', to='paiements.transactionpaiement', verbose_name='Transaction associée'),
        ),
        migrations.AddField(
            model_name='boostvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='videos.video', verbose_name='Vidéo'),
        ),
        migrations.AddIndex(
            model_name='boostvideo',
            index=models.Index(fields=['statut', '-date_debut'], name='boosts_boos_statut_f9f09d_idx'),
        ),
    ]
