# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Référence')),
                ('type_transaction', models.CharField(choices=[('abonnement', "Paiement d'abonnement"), ('boost', 'Achat de boost'), ('renouvellement', "Renouvellement d'abonnement")], max_length=30, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (USD)')),
                ('devise', models.CharField(default='USD', max_length=5, verbose_name='Devise')),
                ('moyen_paiement', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('afri_money', 'Afri Money'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, verbose_name='Moyen de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('reussie', 'Réussie'), ('echouee', 'Échouée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('reference_prestataire', models.CharField(blank=True, default='', max_length=200, verbose_name='Référence prestataire')),
                ('reponse_prestataire', models.JSONField(blank=True, default=dict, verbose_name='Réponse prestataire')),
                ('numero_telephone_paiement', models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro téléphone paiement')),
                ('nombre_tentatives', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de tentatives')),
                ('derniere_tentative', models.DateTimeField(blank=True, null=True, verbose_name='Dernière tentative')),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='paiements/preuves/', verbose_name='Preuve de paiement')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Description')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='abonnements.abonnement', verbose_name='Abonnement lié')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JournalPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=100, verbose_name='Événement')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Détail')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données')),
                ('date_evenement', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='paiements.transactionpaiement', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Journal de paiement',
                'verbose_name_plural': 'Journaux de paiement',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['statut', '-date_creation'], name='paiements_t_statut_7faa78_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['utilisateur', '-date_creation'], name='paiements_t_utilisa_24ce39_idx'),
        ),
    ]
