# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de revue'), ('en_cours', 'En cours de revue'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('correction', 'Correction demandée'), ('suspendue', 'Suspendue')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_agent', models.TextField(blank=True, default='', verbose_name="Commentaire de l'agent")),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_moderation', to=settings.AUTH_USER_MODEL, verbose_name='Agent soumetteur')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_moderation', to='biens.bienimmobilier', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Soumission de modération',
                'verbose_name_plural': 'Soumissions de modération',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='DecisionModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('en_attente', 'En attente de revue'), ('en_cours', 'En cours de revue'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('correction', 'Correction demandée'), ('suspendue', 'Suspendue')], max_length=20, verbose_name='Décision')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif')),
                ('notes_internes', models.TextField(blank=True, default='', verbose_name='Notes internes')),
                ('date_decision', models.DateTimeField(auto_now_add=True, verbose_name='Date de décision')),
                ('moderateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_moderation', to=settings.AUTH_USER_MODEL, verbose_name='Modérateur')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='moderation.soumissionmoderation', verbose_name='Soumission')),
            ],
            options={
                'verbose_name': 'Décision de modération',
                'verbose_name_plural': 'Décisions de modération',
                'ordering': ['-date_decision'],
            },
        ),
    ]
