# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Fichier vidéo')),
                ('url_externe', models.URLField(blank=True, default='', verbose_name='URL vidéo externe')),
                ('cle_stockage', models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage externe')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='videos/miniatures/', verbose_name='Miniature')),
                ('duree_secondes', models.PositiveIntegerField(default=0, verbose_name='Durée (secondes)')),
                ('taille_octets', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('format_video', models.CharField(blank=True, default='mp4', max_length=20, verbose_name='Format')),
                ('resolution', models.CharField(blank=True, default='', max_length=20, verbose_name='Résolution')),
                ('est_verticale', models.BooleanField(default=True, verbose_name='Vidéo verticale')),
                ('nombre_lectures', models.PositiveIntegerField(default=0, verbose_name='Nombre de lectures')),
                ('nombre_lectures_completes', models.PositiveIntegerField(default=0, verbose_name='Lectures complètes')),
                ('duree_visionnage_totale', models.PositiveBigIntegerField(default=0, verbose_name='Durée visionnage totale (sec)')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='biens.bienimmobilier', verbose_name='Bien immobilier')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-date_upload'],
            },
        ),
    ]
