# Generated by Django 5.2.11 on 2026-03-20 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='video',
            name='est_supprime',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='video',
            name='motif_suppression',
            field=models.TextField(blank=True, default='', verbose_name='Motif de suppression'),
        ),
        migrations.AddField(
            model_name='video',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_supprimees', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
    ]
