# Generated by Django 5.2.11 on 2026-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMensuelleNotable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('date_action', models.DateField(verbose_name="Date de l'action")),
                ('impact', models.CharField(blank=True, default='', max_length=100, verbose_name='Impact')),
            ],
            options={
                'verbose_name': 'Action mensuelle notable',
                'verbose_name_plural': 'Actions mensuelles notables',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='FicheTravailMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures travaillées')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures supplémentaires')),
                ('salaire_base_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salaire de base (USD)')),
                ('prime_heures_sup_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prime heures sup (USD)')),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (USD)')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Fiche de travail mensuel',
                'verbose_name_plural': 'Fiches de travail mensuel',
                'ordering': ['-annee', '-mois'],
            },
        ),
    ]
