# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetravailmensuel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_travail', to='comptes.profiladministrateur', verbose_name='Administrateur'),
        ),
        migrations.AddField(
            model_name='fichetravailmensuel',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='actionmensuellenotable',
            name='fiche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_notables', to='administration.fichetravailmensuel', verbose_name='Fiche mensuelle'),
        ),
        migrations.AlterUniqueTogether(
            name='fichetravailmensuel',
            unique_together={('admin', 'mois', 'annee')},
        ),
    ]
