# Generated by Django 5.2.11 on 2026-03-18 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(blank=True, default='', verbose_name='Valeur')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Description')),
                ('type_donnee', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('booleen', 'Booléen'), ('json', 'JSON')], default='texte', max_length=20, verbose_name='Type de donnée')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètre de plateforme',
                'verbose_name_plural': 'Paramètres de plateforme',
                'ordering': ['cle'],
            },
        ),
    ]
