# Generated by Django 5.2.11 on 2026-03-20 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_parametreplateforme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('cible', models.CharField(choices=[('tous', 'Tous les utilisateurs'), ('specifique', 'Utilisateur spécifique')], default='tous', max_length=20, verbose_name='Cible')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('destinataire', models.ForeignKey(blank=True, help_text='Rempli uniquement si cible = spécifique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('envoye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Preoccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('compte', 'Mon compte'), ('paiement', 'Paiement / Abonnement'), ('technique', 'Problème technique'), ('signalement', 'Signalement'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('traitee', 'Traitée'), ('fermee', 'Fermée')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('reponse', models.TextField(blank=True, default='', verbose_name='Réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preoccupations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preoccupations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préoccupation',
                'verbose_name_plural': 'Préoccupations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
