# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('essai', 'Essai gratuit'), ('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], db_index=True, default='essai', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('est_essai_gratuit', models.BooleanField(default=False, verbose_name='Essai gratuit')),
                ('renouvellement_auto', models.BooleanField(default=False, verbose_name='Renouvellement automatique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CycleAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_cycle', models.DateTimeField(verbose_name='Début du cycle')),
                ('date_fin_cycle', models.DateTimeField(verbose_name='Fin du cycle')),
                ('publications_utilisees', models.PositiveIntegerField(default=0, verbose_name='Publications utilisées')),
                ('boosts_utilises', models.PositiveIntegerField(default=0, verbose_name='Boosts utilisés')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Cycle actif')),
            ],
            options={
                'verbose_name': "Cycle d'abonnement",
                'verbose_name_plural': "Cycles d'abonnement",
                'ordering': ['-date_debut_cycle'],
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True, verbose_name='Nom du plan')),
                ('prix_mensuel_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix mensuel (USD)')),
                ('nombre_publications_max', models.PositiveIntegerField(default=10, help_text='0 = illimité', verbose_name='Publications max / mois')),
                ('nombre_boosts_inclus', models.PositiveIntegerField(default=5, help_text='0 = illimité', verbose_name='Boosts inclus / mois')),
                ('messages_illimites', models.BooleanField(default=True, verbose_name='Messages illimités')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Plan actif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
