# Generated by Django 5.2.11 on 2026-03-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'type_compte': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='cycleabonnement',
            name='abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='abonnements.abonnement', verbose_name='Abonnement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.planabonnement', verbose_name='Plan'),
        ),
    ]
